MVCAssignment1/Models/ErrorViewModel.cs
namespace MVCAssignment1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCAssignment1/Models/Product.cs
namespace MVCAssignment1.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Price { get; set; }  

    }
}

MVCAssignment1/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.InteropServices;

namespace Assignment.Controllers
{
    public class CourseController : Controller
    {
        [HttpGet]

        public IActionResult CourseDetails()
        {
            List<string> Options = new List<string>()
            {
                "Java" , "C#" , "React" , "Angular" , "Software Testing"
            };

            ViewData["Options"] = new SelectList(Options);
            return View();
        }
        [HttpPost]
        public IActionResult CourseDetails(IFormCollection form)
        {

            ViewBag.Name = form["Name"];
            ViewBag.Gender = form["gender"];
            ViewBag.Options = form["Options"];
            ViewBag.course = form["course"];
            return View("DisplayCourseDetails");
        }
    }
}

MVCAssignment1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCAssignment1.Models;
using System.Diagnostics;

namespace MVCAssignment1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<string> colors = new List<string>()
            {
                "Red","Black","White","Blue","Orange"
            };
            ViewData["list"] = colors; // implict --> object
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCAssignment1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVCAssignment1.Models;

namespace MVCAssignment1.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            
            List<Product> products = new List<Product>
        {
            new Product { Id = 1, Name = "Sofa", Price = 100 },
            new Product { Id = 2, Name = "Table", Price = 200 },
            new Product { Id = 3, Name = "Chair", Price = 300 }
        };

            
            ViewData["Message"] = "This is the product list";

           
            ViewBag.Products = products;

            return View();
        }
    }
}

MVCAssignment1/Views/Course/CourseDetails.cshtml
@{
    ViewData["Title"] = "CourseDetails";
}

<h1>Course Details</h1>

@using (Html.BeginForm())
{
    <table>

        <tr>
            <td>Enter your Name</td>
            <td>
                @Html.TextBox("Name")
            </td>
        </tr>

        <tr>
            <td>Select Gender</td>
            <td>
                @Html.RadioButton("gender" , "Male") Male
                @Html.RadioButton("gender" , "Female") Female
            </td>
        </tr>






        <tr>
            <td>Select course</td>
            <td>
                <input type="checkbox" name="course" value="java" /> Java
                <input type="checkbox" name="course" value="C#" /> C#
                <input type="checkbox" name="course" value="React" />React
                <input type="checkbox" name="course" value="Software Teating" />Software Testing
                <input type="checkbox" name="course" value="Angular" />Angular
            </td>
        </tr>
        <tr>
            <td>Would you like to know more about the course?</td>
            <td>@Html.DropDownList("Options")</td>
        </tr>



        <tr>
            <td></td>
            <td>
                <input type="submit" value="save" />
            </td>
        </tr>

    </table>
}

MVCAssignment1/Views/Course/DisplayCourseDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "DisplayCourseDetails";
}

<h1>Display Course Details</h1>

<table class="table">
    <tr>
        <td>Name</td>
        <td>
            @ViewBag.Name
        </td>
    </tr>

    <tr>
        <td>Gender</td>
        <td>
            @ViewBag.Gender
        </td>
    </tr>


    <tr>
        <td>Course Option</td>
        <td>
            @ViewBag.Options
        </td>
    </tr>
    </tr>
    <tr>
        <td>Selected Course Details</td>
        <td>
            @foreach (string s in ViewBag.course)
            {
                <p>@s</p>
            }
        </td>
    </tr>


</table>

MVCAssignment1/Views/Course/ShowDetails.cshtml
@using (Html.BeginForm())
{


    <table>
        <tr>
            <td>Enter your name</td>
            <td>
                @Html.TextBox("username")
            </td>
        </tr>
        <tr>
            <td>Select Gender</td>
            <td>
                @Html.RadioButton("gender","Male") Male
                @Html.RadioButton("gender","Female") Female
            </td>
        </tr>
        <tr>
            <td>Select Interested</td>
            <td>
                <input type="checkbox" name="course" value="C#" /> C#
                <input type="checkbox" name="course" value="Java" /> Java
                <input type="checkbox" name="course" value="Python" /> Python
            </td>
        </tr>
        <tr>
            <td>Would You Like To Know MoreAbout The Course</td>
            <td>
                @Html.DropDownList("option")
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add" />
            </td>
        </tr>
    </table>


}

MVCAssignment1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1> Colors </h1>

@if (ViewData["list"] != null)
{
    <ol>
        @foreach (string str in (IEnumerable<string>)ViewData["list"])
        {
            <li>
                @str
            </li>
        }
    </ol>
}

MVCAssignment1/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Product List";
}

<h2>@ViewData["Message"]</h2>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
    </tr>
    @foreach (var product in ViewBag.Products)
    {
        <tr>
            <td>@product.Id</td>
            <td>@product.Name</td>
            <td>@product.Price.ToString()</td>
        </tr>
    }
</table>

MVCAssignment1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCAssignment1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCAssignment1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCAssignment1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="CourseDetails">Course Details List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCAssignment1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>